# -------------------部署需要修改---------------------
bots:
  config:
    logs: false
    enable-proxy: false
    enable-bot: false


# -------------------部署需要修改---------------------

mybatis-plus:
  mapper-locations: classpath:/mapper/**.xml
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: true

  global-config:
    # 全局配置
    banner: false
    db-config:
      table-prefix: t_
      # 数据库配置
      id-type: auto

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Qj683k2^11299%nkjb
    url: jdbc:mysql://127.0.0.1:3306/kuaisou_ai_bot?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: Qj683k2^11299%nkjb
  elasticsearch:
    uris:
      - http://127.0.0.1:9200
    username: elastic
    password: umEjOIAMYkf3vPq9YEaB
    connection-timeout: 5000
    socket-timeout: 60000
  data:
    elasticsearch:
      repositories:
        enabled: true

logging:
  level:
    org.drinkless.robots: info
    org.springframework.data.elasticsearch: info
    org.elasticsearch.client: info